best_params:
  eval_metric: "MAPE"
  bootstrap_type: MVS
  iterations: '200000'
  learning_rate: '0.01'
  early_stopping_rounds: '10000'
  depth: '10'
cat_features:
- origin_kma
- destination_kma
- transport_type
selected_features:
- valid_miles
- transport_type
- origin_kma
- destination_kma
- rate_similar_1
- rate_similar_2
- rate_similar_3
- rate_similar_8
- rate_similar_9
- rate_similar_10
- order_index
- pickup_date_unix_ratio
