best_params:
  boosting_type: Plain
  bootstrap_type: MVS
  depth: '8'
  iterations: '10000'
  early_stopping_rounds: '1000'
  l2_leaf_reg: '3.8'
  learning_rate: '0.05'
  min_data_in_leaf: '20'
  rsm: '1.0'
cat_features:
- transport_type
- origin_kma
- destination_kma
selected_features:
- transport_type
- latest_rate_2nd
- ewma_120d
- valid_miles
- mean_rate_120d
- latest_rate
- origin_kma
- mean_rate_30d
- ewma_30d
- destination_kma
- mean_rate_90d
- ewma_90d
